### ISSUE TITLE
PNG transparency 

### ISSUE THREAD

**Issue by jeroen69** [mozilla/badg.us#2]
This issue was raised in a different /not the right place before: 

https://github.com/mozilla/badges.mozilla.org/issues/34

The solution appears to be in the thread, but was only applied to badges.mozilla.org and not yet to badge.us

Any chance someone is able to perform the same magic here?

Please do let me know if there's any comments or questions. 

Cheers, 
Jeroen

**Comment by jeroen69** [comment]
I was happy to read an announcement in the open bagde google group that badg.us is up and running again. Any idea when/if this png transparency fix can be incorporated?

Looking forward to pilot a badges approach in my organisation :-) Anything I can do to help?

**Comment by MiriamTuohy** [comment]
I have exactly the same problem with my badge images on badg.us - png files look fine (first image here is how they look in gDrive folder) but when uploaded to badg.us they have a black background (second image).
![image](https://f.cloud.github.com/assets/6219864/1780051/2d0da576-6861-11e3-8a74-e0c71f9a929d.png)
![image](https://f.cloud.github.com/assets/6219864/1780057/395e0ae6-6861-11e3-9b7f-2ce89bd5cb31.png)

Any suggestions as to why this might be happening? Or ideas for fixing it? would be very grateful for info that can help me solve the problem.

Thanks,
Miriam

**Comment by jeroen69** [comment]
Do I understand correctly that there is currently no work done on badg.us @cmcavoy ?

Thanks for enlightening me :-) Cheers, Jeroen

**Comment by threeqube** [comment]
@jeroen69 We are doing some amount of work on Badg.us but have to do it in our spare time since there is no dedicated team working on it.

**Comment by jeroen69** [comment]
Ah ok, thanks for letting me know. Keep up the good work! :-) Happy New Year!

**Comment by threeqube** [comment]
Thanks!

**Comment by LearnTribe** [comment]
Hi,
As an open source contributor I completely understand not having a dedicated team slows things down - but if someone could spare 5-10 minutes to implement the minor bugfix it would be much appreciated. I hoped to use badg.us as the issuer for a free learning conference and user group but would need to modify all the badges and lose transparency.
Link to the bugfix code from discussion thread - https://github.com/mozilla/django-badger/commit/270895fa44c3e6df5ec6430cb593d41841aebe89
Thanks.
