### ISSUE TITLE
point users of badg.us to this issue tracker for issues

### ISSUE THREAD

**Issue by willkg** [mozilla/badg.us#3]
We're seeing issues for badg.us being reported in the issue tracker for badges.mozilla.org and the issue tracker for django-badger. Neither place is a good place for badg.us issues.

Please update the badg.us site text to point users to this issue tracker for badg.us issues.

**Comment by threeqube** [comment]
cc/ing @cmcavoy

**Comment by cmcavoy** [comment]
Got it, we'll clean up the link and get it launched.

On Tue, Nov 19, 2013 at 11:46 AM, threeqube notifications@github.comwrote:

> cc/ing @cmcavoy https://github.com/cmcavoy
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/badg.us/issues/3#issuecomment-28814342
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by cmcavoy** [comment]
updated the readme to point people to this issue repo.
