### ISSUE TITLE
Research who the current user base is for badg.us

### ISSUE THREAD

**Issue by iamjessklein** [mozilla/badg.us#4]
We are interested in learning:
- who is using badg.us?
- how are they using it?
- what features are they using the most?
- what features are they using the least?
- how are they finding badg.us?
- what are their wishlist features?

**Comment by emgollie** [comment]
Let's discuss this tomorrow if you have a minute @iamjessklein. These questions surround a larger question (and ongoing conversation with @cmcavoy @carlacasilli) around separating badges.mozilla.org and badg.us. I got some use case information surrounding the latter in my interview with Michael Boll from the international school in Shanghai--he needs an open source tool for conferences the school is affiliated with and is helping file some badg.us bugs.

**Comment by iamjessklein** [comment]
badg.us is slated to become the "nightly" for badgekit- however, we want to understand what is happening with badg.us before making any big moves with the design and/or data so we need to do a little research on the existing user base.

cc/ @threeqube @cmcavoy

**Comment by threeqube** [comment]
Agreed.

**Comment by emgollie** [comment]
Per a conversation with @iamjessklein, I'm writing up a research plan for Badg.us use case collection extending into early Q1 (https://openbadges.etherpad.mozilla.org/badgus-research). @cmcavoy, can I work with you to understand what visitor information we have since we took over control of the site? I know that Les said he didn't have these details, but might you be able to tell me if we have any usage information that we can start with? Thanks.

**Comment by cmcavoy** [comment]
@emgollie you bet...I can either give you access to the admin panel for the site, or you can work on a list of questions and we can figure them out together. Whichever is easiest for you.

KNOWLEDGE IS POWER. ONE TO GROW ON.

![ONE TO GROW ON](http://likethe8os.files.wordpress.com/2012/12/tumblr_m5kt3djsve1rrspk8o3_400.jpg)

**Comment by iamjessklein** [comment]
:neckbeard:

**Comment by emgollie** [comment]
Thanks for the in-pad feedback @iamjessklein. 

@cmcavoy, would you mind giving admin access and I take a look and reach out with questions? (I am likely to have lots. Including: do KIPP schools mean "Knowledge is Power Program"?)

**Comment by emgollie** [comment]
@cmcavoy, per our chat would you mind letting me know where on the badg.us site I should be going to dig into user info? Settings are taking me to my own badges and the opportunity to issue (vs. look at admin data). Thanks! 

![screen shot 2013-12-03 at 3 35 09 pm](https://f.cloud.github.com/assets/1174853/1669183/9acc63da-5c73-11e3-82fa-5725fc2eeec6.png)

**Comment by cmcavoy** [comment]
Hey @emgollie /admin

**Comment by emgollie** [comment]
Thanks @cmcavoy. Is "superuser status" something Les set parameters for, or is that a pre-set status that's built in?

#n00b #ninja

**Comment by cmcavoy** [comment]
pre-set status, part of the Django Admin...

On Tue, Dec 3, 2013 at 5:46 PM, Emily Goligoski notifications@github.comwrote:

> Thanks @cmcavoy https://github.com/cmcavoy. Is "superuser status"
> something Les set parameters for, or is that a pre-set status that's built
> in?
> 
> #n00b #ninja
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mozilla/badg.us/issues/4#issuecomment-29764058
> .

## 

@chmcavoy http://twitter.com/chmcavoy
http://lonelylion.com

**Comment by emgollie** [comment]
@cmcavoy @iamjessklein @threeqube I want to propose holding on badg.us issuer & motivation research for the time being (we don't have a a non-@cmcavoy nighttime fixes plan for supporting it yet) to focus on BadgeKit cities work. This isn't a cancellation of this work, just postponing it until we know better where/how Badg.us will operate.

Some of the issues that Badg.us users are filing (https://github.com/mozilla/badg.us/issues) and their complaints over email have been enlightening about their needs. At this moment, I think we are more in divide and conquer mode than anything. Move to temporarily close if others agree.
