### ISSUE TITLE
Blank page after badge creation

### ISSUE THREAD

**Issue by dajbelshaw** [mozilla/badg.us#5]
After creating a badge the user is directed to a completely blank page. Hitting 'back' and trying to recreate the badge leads to a message saying the badge has already been created.

Sure enough, it's there in the user profile and works fine, but there's something broken here.

**Comment by Michaelboll** [comment]
Here is a video of this issue: https://www.youtube.com/watch?v=BvpuI0i37tI

This has been a problem since September or so.   Thanks for taking over on this issue Mozilla!!

**Comment by cmcavoy** [comment]
Update - still investigating. Will be getting logs from production soon, which will help.
