### ISSUE TITLE
Request to understand claim codes not being received 

### ISSUE THREAD

**Issue by emgollie** [mozilla/badg.us#7]
From Katherine Naszradi re: the student ambassador badges she's issued:

Several people have reported not receiving the badges after they have been issued. Thus far, we've been asking them to check their spam folder and see if they can find it there and then re-sending to them again (to some success). If you have any guidance on a better way to send the badges (so that they will be received), that would be lovely. I'm including my current process below in case there's any errors that you can correct:
1. Log-in here: http://badg.us/en-US/badges/badge/Firefox-Student-Ambassador-Badge
2. Generate one reusable code 
3. Click on the badge code 
4. Enter email address
5. Click 'Grant this award'

cc @cmcavoy

**Comment by emgollie** [comment]
Per discussion with @threeqube @cmcavoy yesterday, Katherine reports:

"Just re-sent and I think I actually may have figured out the problem. It works to distribute the badges from the main dashboard but I think the problem lies when you generate the claim codes and try to send the awards through clicking on the claim code and then entering the email address. Does that make sense? "

I received the badge via both Gmail and MoFo email this morning.

**Comment by cmcavoy** [comment]
That helps narrow it down...will investigate.
